application: coisinhasfofas-microerp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: microerp/static
- url: /.*
  script: microerp.main.app
  login: required

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (index\.yaml)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (env/*)|
 )$